apiVersion: v1
kind: Service
metadata:
  name: mysql-container     
  namespace: drupal-lab
spec:
  type: ClusterIP
  selector:
    app: database          
  ports:
    - port: 3306
      targetPort: 3306
